spring.application.name=LottoApi

lotto-api.base-url=https://developers.lotto.pl/api/open/v1/lotteries
lotto-api.secret=

spring.datasource.url=jdbc:postgresql://localhost:5432/lotto
spring.datasource.username=
spring.datasource.password=

spring.jpa.show-sql=true