CREATE TABLE draw_prize
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    draw_system_id BIGINT,
    game_type      SMALLINT                                NOT NULL,
    draw_date      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_drawprize PRIMARY KEY (id)
);

CREATE TABLE prize
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    degree        INTEGER          NOT NULL,
    winners_count INTEGER          NOT NULL,
    value         DOUBLE PRECISION NOT NULL,
    draw_prize_id BIGINT           NOT NULL,
    CONSTRAINT pk_prize PRIMARY KEY (id)
);

ALTER TABLE prize
    ADD CONSTRAINT FK_PRIZE_ON_DRAW_PRIZE FOREIGN KEY (draw_prize_id) REFERENCES draw_prize (id);